// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlcInterface.Context;

namespace PlcInterface.Migrations.Mes
{
    [DbContext(typeof(MesContext))]
    [Migration("20210809151313_AddUtilitiesTank")]
    partial class AddUtilitiesTank
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.Boiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("FactoryId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("Boilers");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.Compressor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("FactoryId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("Compressors");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.Factory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.Load", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("BoilerId")
                        .HasColumnType("int");

                    b.Property<int?>("CompressorId")
                        .HasColumnType("int");

                    b.Property<string>("EnergyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FactoryId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlcCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductionLineId")
                        .HasColumnType("int");

                    b.Property<string>("SignalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TankId")
                        .HasColumnType("int");

                    b.Property<int?>("UtilityId")
                        .HasColumnType("int");

                    b.Property<int?>("WaterChemicalTreatmentId")
                        .HasColumnType("int");

                    b.Property<int?>("WaterPumpId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoilerId");

                    b.HasIndex("CompressorId");

                    b.HasIndex("FactoryId");

                    b.HasIndex("ProductionLineId");

                    b.HasIndex("TankId");

                    b.HasIndex("UtilityId");

                    b.HasIndex("WaterChemicalTreatmentId");

                    b.HasIndex("WaterPumpId");

                    b.ToTable("Loads");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.MachineParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("MachineCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MachineParameters");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.ProductionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("FactoryId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("ProductionLines");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.Tank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("FactoryId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("Tanks");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.Utility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("FactoryId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("Utilities");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.WaterChemicalTreatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("FactoryId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("WaterChemicalTreatments");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.WaterPump", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("FactoryId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.ToTable("WaterPumps");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.Boiler", b =>
                {
                    b.HasOne("PlcInterface.Models.CocaMesModels.Factory", "Factory")
                        .WithMany()
                        .HasForeignKey("FactoryId");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.Compressor", b =>
                {
                    b.HasOne("PlcInterface.Models.CocaMesModels.Factory", "Factory")
                        .WithMany()
                        .HasForeignKey("FactoryId");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.Load", b =>
                {
                    b.HasOne("PlcInterface.Models.CocaMesModels.Boiler", "Boiler")
                        .WithMany("Loads")
                        .HasForeignKey("BoilerId");

                    b.HasOne("PlcInterface.Models.CocaMesModels.Compressor", "Compressor")
                        .WithMany("Loads")
                        .HasForeignKey("CompressorId");

                    b.HasOne("PlcInterface.Models.CocaMesModels.Factory", "Factory")
                        .WithMany("Loads")
                        .HasForeignKey("FactoryId");

                    b.HasOne("PlcInterface.Models.CocaMesModels.ProductionLine", "ProductionLine")
                        .WithMany("Loads")
                        .HasForeignKey("ProductionLineId");

                    b.HasOne("PlcInterface.Models.CocaMesModels.Tank", "Tank")
                        .WithMany("Loads")
                        .HasForeignKey("TankId");

                    b.HasOne("PlcInterface.Models.CocaMesModels.Utility", "Utility")
                        .WithMany("Loads")
                        .HasForeignKey("UtilityId");

                    b.HasOne("PlcInterface.Models.CocaMesModels.WaterChemicalTreatment", "WaterChemicalTreatment")
                        .WithMany("Loads")
                        .HasForeignKey("WaterChemicalTreatmentId");

                    b.HasOne("PlcInterface.Models.CocaMesModels.WaterPump", "WaterPump")
                        .WithMany("Loads")
                        .HasForeignKey("WaterPumpId");

                    b.Navigation("Boiler");

                    b.Navigation("Compressor");

                    b.Navigation("Factory");

                    b.Navigation("ProductionLine");

                    b.Navigation("Tank");

                    b.Navigation("Utility");

                    b.Navigation("WaterChemicalTreatment");

                    b.Navigation("WaterPump");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.ProductionLine", b =>
                {
                    b.HasOne("PlcInterface.Models.CocaMesModels.Factory", "Factory")
                        .WithMany("ProductionLines")
                        .HasForeignKey("FactoryId");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.Tank", b =>
                {
                    b.HasOne("PlcInterface.Models.CocaMesModels.Factory", "Factory")
                        .WithMany()
                        .HasForeignKey("FactoryId");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.Utility", b =>
                {
                    b.HasOne("PlcInterface.Models.CocaMesModels.Factory", "Factory")
                        .WithMany("Utilities")
                        .HasForeignKey("FactoryId");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.WaterChemicalTreatment", b =>
                {
                    b.HasOne("PlcInterface.Models.CocaMesModels.Factory", "Factory")
                        .WithMany()
                        .HasForeignKey("FactoryId");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.WaterPump", b =>
                {
                    b.HasOne("PlcInterface.Models.CocaMesModels.Factory", "Factory")
                        .WithMany()
                        .HasForeignKey("FactoryId");

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.Boiler", b =>
                {
                    b.Navigation("Loads");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.Compressor", b =>
                {
                    b.Navigation("Loads");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.Factory", b =>
                {
                    b.Navigation("Loads");

                    b.Navigation("ProductionLines");

                    b.Navigation("Utilities");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.ProductionLine", b =>
                {
                    b.Navigation("Loads");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.Tank", b =>
                {
                    b.Navigation("Loads");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.Utility", b =>
                {
                    b.Navigation("Loads");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.WaterChemicalTreatment", b =>
                {
                    b.Navigation("Loads");
                });

            modelBuilder.Entity("PlcInterface.Models.CocaMesModels.WaterPump", b =>
                {
                    b.Navigation("Loads");
                });
#pragma warning restore 612, 618
        }
    }
}
